### ISSUE TITLE
Tests fail with lfe test running but pass with rebar3 eunit ...

### ISSUE THREAD

**Issue by oubiwann** [lfex/kla#6]
This issue arises when using `rebar3 as test lfe test`, not when using `rebar3 as test eunit`.

Additionally, 
- Tests aren't found with `{eunit_compile_opts, [{src_dirs, ["src", "test"]}]}`
- They are only found when setting `{erl_opts, [{src_dirs, ["src", "test"]}]}.`

Again, that only applies when using `rebar3 as test lfe test`; the rebar config options work as expected when running tests with `rebar3 as test eunit`.

Not sure what's going on :-/

**Comment by yurrriq** [comment]
Possibly related: https://github.com/erlang/rebar3/issues/1331

**Comment by oubiwann** [comment]
This has been fixed:
- https://github.com/lfe-rebar3/test/issues/1

Latest kla release (0.8.0-rc3) has applied the fixes.
